---
collections:
  - name: infra.controller_configuration
    version: 2.3.1
  - name: infra.ah_configuration
  - name: infra.ee_utilities
  - name: infra.aap_utilities
  - name: containers.podman
  # Commented out until CI/CD can get fixed
  # - name: ansible.controller
  - name: awx.awx
...
