---
controller_credentials_all:
  - name: aap_admin
    credential_type: Red Hat Ansible Automation Platform
    organization: config_as_code
    description: aap admin account
    inputs:
      host: "{{ controller_hostname }}"
      username: "{{ controller_username }}"
      password: "{{ controller_password }}"
      verify_ssl: false

  - name: root
    credential_type: Machine
    organization: config_as_code
    description: root local password
    inputs:
      username: root
      password: "{{ root_machine_pass }}"

  - name: vault
    credential_type: Vault
    organization: config_as_code
    description: vault password
    inputs:
      vault_password: "{{ vault_pass }}"

  # here is an example for getting git ssh cred working
  # - name: github
  #   credential_type: Source Control
  #   organization: config_as_code
  #   description: github
  #   inputs:
  #     username: ""
  #     ssh_key_data: "{{ ssh_priv_key }}"
  #     ssh_key_unlock: "{{ ssh_key_unlock }}"
...
