---
controller_templates_all:
  - name: controller_config
    project: config_as_code
    job_type: run
    playbook: playbooks/controller_config.yml
    inventory: config_as_code
    execution_environment: Default execution environment
    concurrent_jobs_enabled: false
    ask_variables_on_launch: true
    limit: "{{ env }}"
    verbosity: 0
    credentials:
      - aap_admin
      - vault
    extra_vars:
      # for debugging errors with creds change to false
      controller_configuration_credentials_secure_logging: true

  - name: console_token_refresh
    project: config_as_code
    job_type: run
    playbook: playbooks/console_token_refresh.yml
    inventory: config_as_code
    execution_environment: Minimal execution environment
    concurrent_jobs_enabled: false
    limit: "{{ env }}"
    verbosity: 0
    credentials:
      - vault
...
